sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        xmcyh86thv4Wu0YOZWGB/7YEwpoOnXG+fqU78BKLTVGxdCtLZzk+drQqK6VXpysZGIibRXXJveZOailhwUALwaTEGje9+9eVR5yvE440Cerx4DzdvkMiBbOYt5Kes8r2BKyRZTuBGRWPasumLQDxDdAPh2SGV2drnrfaSGgmg3VOYY/bXzwUjCohKsIrG9+rQnyAiXXkTVB4yWw1z88AF9eMiZEbiaZEsc+OIYU1yiSBRV5C2473kF1GY28FE36ShZZYYzoNZu5qwWGAffeT9DXe/gQpa8wMaa2ol2t4gPlDAPXVOz9CJ4Uu09d/WX7oa07JL5fHPZ7o4vwHbEUe9ygmbo/+UF68YLhYB7YMx5KKNFpiAJ08S9W/npMIo29eY7bCdENchgzu4r92YHdXr8vFZfGflqjIeVVISbqn0N/1p7yB6P1tuxkHq7m434VGBjWbEuyqiCBg+aoUsoKUlF1rPGb1m7+Ap6ryEmOesQyT7gNGeTjaQt658Ogr/73Q/nOLWXO2x1uUDej8eQFIqVBIhFiO1cOMERjf/X0RCCeOkepS2xev1gLvZcAiGFg4+yKFcmTGXtHSubeFA5kedoQXe0ShUwHIyuXkPgiAfqG+EdZKTF3hVQkOR4qUV+k7+V0fGdjjNoPUsNgRnWwaRrkyp6yqlReGdFMCnc9AvEU=
    - secure: >-
        xOjFsI9/k2kj4xkWYPDy+4uccQ5GFPoWvADkM5WGvYZsadavhYnnS9HXOe5a50cRtzhbUCVtj84FBLv/druCcExmgZ9jtOSI8tM7QcrCTF0SuNz5tWDKitYxe15EpN/NsiYO6fsGGR9t8W/NnItXsoTLCruhaxcoH6Ezhun2CitbQGdY5LM2VEWoHSGSN0ezjpn6RiVEfcKYtR0UF2V6mRUHF9LWh8lEEtIBs8h3mUorMKk9p8FkrxepRya8N0W6viCGaAMW1XI6Fx3D1O6KZBH1FG20FOTY3FJZX3z2SUtf5vp7L+yp4KcDerbkjLlAm0vpqSGpxPC8otzz2xxnyLBqFq/5R/16QJAyB2uZPfoEU8Wc6S03FhIhUzxa6jnuaW8aJIZ8BBquabb07tHwYnE683dRM7gGzh04o3RokNVv4cXEGzOoQGrcRBdd8H6Iux3jbHyJ1GZlksd8SSb2DPyuIYJ/2s1By+AJNnV7ll80T/fyStAejegClOsPVh2nK52Ho+9kNRa9DyeEqugfIAB0OjtTzx6od5Daxs3paPK1KT9tPYveaFCzitQwi8/1uBbcjSZgHZVymN0AHhFOPDo9IMs4yFguO5sErhCQ/3JgFBfvYbkrsK/Q5TSV34Set26fDRZXeXGvJ6Ld0FeJii23KKZn/1mluLvlyGgQ1j8=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
